import type { Metadata } from "next"
import { Inter, Red_Hat_Display, Poppins, Lato } from "next/font/google"
import Header from "../components/Header"
import Footer from "../components/Footer"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const redHat = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["300", "900"],
  variable: "--font-red-hat",
})

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "900"],
  variable: "--font-lato",
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "900"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${inter.variable} ${redHat.variable} ${lato.variable} ${poppins.variable} antialiased overflow-x-hidden`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
